import {
  existsSync,
  mkdirSync,
  rmSync,
  writeFileSync,
} from 'fs';
import { join, relative } from 'path';
import dedent from 'ts-dedent';

import { Rule, rules, RuleType, sortRules } from '../../src/rules';
import '../../src/rules-registry';

/**
 * Generates integration-test suites and their corresponding test-vault
 * fixtures from the examples defined on each rule.
 *
 * Generated integration suites:
 *   __integration__/rule-tests/<rule-alias>.test.ts
 *
 * Generated test-vault files:
 *   test-vault/rule-tests/<rule-alias>/<rule-alias>-<example-number>.md
 *   test-vault/rule-tests/<rule-alias>/<rule-alias>-<example-number>.linted.md
 *
 * The generated directories are deleted and recreated on every run.
 */

const integrationTestsDirectory = './__integration__/rule-tests';
const testVaultDirectory = './test-vault/rule-tests';

const autogenWarning = `// This file was automatically generated. Do not edit it directly.\n` +
  `// Generated by scripts/js/integration-tests.ts.\n\n`;

const skipRules = new Set<string>([
  'yaml-timestamp', // uses moment
  'yaml-key-sort', // uses moment
]);

sortRules();

generate();

function generate(): void {
  recreateDirectory(integrationTestsDirectory);
  recreateDirectory(testVaultDirectory);

  const rulesAliasesForTestCases: string[] = [];
  for (const rule of rules) {
    if (shouldSkipRule(rule)) {
      console.log(`Skipping ${rule.alias}`);
      continue;
    }

    rulesAliasesForTestCases.push(rule.alias);
    generateRule(rule);
  }

  generateIndex(rulesAliasesForTestCases);

  console.log('Integration tests generated.');
}

function shouldSkipRule(rule: typeof rules[number]): boolean {
  if (rule.type === RuleType.PASTE || skipRules.has(rule.alias)) {
    return true;
  }

  /*
   * Some rules depend on Moment without necessarily exposing that fact
   * through their rule type. Keep the check here deliberately conservative
   * so those rules can be added to the skip list explicitly when needed.
   */
  return false;
}

function generateIndex(ruleAliases: string[]): void {
  const imports: string[] = [];
  const testCaseSuiteNames: string[] = [];
  for (const ruleAlias of ruleAliases) {
    const testSuiteName = getTestCaseExportName(ruleAlias);
    imports.push(`import { ${testSuiteName} } from './${ruleAlias}.test';`);
    testCaseSuiteNames.push('...' + testSuiteName);
  }

  const outputPath = join(integrationTestsDirectory, `index.ts`);

  writeFileSync(outputPath, dedent`
    ${autogenWarning}${imports.join('\n')}

    export const ruleTests = [
      ${testCaseSuiteNames.join(',\n')}
    ];
  `)
}

function generateRule(rule: Rule): void {
  const ruleDirectory = join(testVaultDirectory, rule.alias);

  mkdirSync(ruleDirectory, { recursive: true });

  const setupFunctions: string[] = [];
  const testCases = rule.examples.map((example, index) => {
    const exampleNumber = index + 1;
    const beforePath = join(ruleDirectory, `${rule.alias}-${exampleNumber}.md`);
    const afterPath = join(ruleDirectory, `${rule.alias}-${exampleNumber}.linted.md`);

    writeFileSync(beforePath, ensureTrailingNewline(example.before));
    writeFileSync(afterPath, ensureTrailingNewline(example.after));

    const [setupFuncName, setupFunc] = generateSetupFunction(rule, example, exampleNumber);
    if (setupFunc) {
      setupFunctions.push(setupFunc);
    }

    return generateTestCase(rule.alias, example, exampleNumber, setupFuncName);
  });

  const testFile = dedent`
    ${autogenWarning}import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

    ${setupFunctions.join('\n\n')}

    export const ${getTestCaseExportName(rule.alias)}: IntegrationTestCase[] = [
      ${testCases.join(',\n')}
    ];
  `;

  const outputPath = join(integrationTestsDirectory, `${rule.alias}.test.ts`);

  writeFileSync(outputPath, testFile);

  console.log(`Generated ${relative(process.cwd(), outputPath)} (${rule.examples.length} example${rule.examples.length === 1 ? '' : 's'})`,
  );
}

function generateTestCase(ruleAlias: string, example: typeof rules[number]['examples'][number], exampleNumber: number, setupFuncName: string): string {
  const filePath = `rule-tests/${ruleAlias}/${ruleAlias}-${exampleNumber}.md`;

  return dedent`
    {
      name: ${JSON.stringify(example.description)},
      filePath: ${JSON.stringify(filePath)},
      setup: ${setupFuncName},
    }
  `;
}

function generateSetupFunction(rule: Rule, example: typeof rules[number]['examples'][number], exampleNumber: number): [setupFuncName: string, setupFunction: string] {
  const funcName = 'setup' + exampleNumber;

  /*
   * Rule examples currently contain the complete before/after text, but not
   * necessarily a complete settings object. The rule itself must always be
   * enabled for the generated integration test.
   *
   * If an example supplies settings, those are emitted into the generated
   * setup function below.
   */
  const settings = getExampleSettings(rule, example);
  if (settings === null) {
    return [funcName, dedent`
        function ${funcName}(plugin: TestLinterPlugin): Promise<void> {
        plugin.plugin.settings.ruleConfigs['${rule.alias}'] = {
          'enabled': true,
        };

        return Promise.resolve();
      }
    `];
  }

  settings['enabled'] = true;

  return [funcName, dedent`
    function ${funcName}(plugin: TestLinterPlugin): Promise<void> {
      plugin.plugin.settings.ruleConfigs['${rule.alias}'] = ${JSON.stringify(settings, null, 2)};

      return Promise.resolve();
    }
  `];
}

function getExampleSettings(rule: Rule, example: typeof rules[number]['examples'][number]): Record<string, unknown> | null {
  /*
   * Rule examples in the current codebase expose before/after/description.
   * This helper intentionally supports an optional settings/options property
   * so the generator will automatically use it if examples gain one without
   * changing the generated-test format.
   */
  const candidate = example as typeof example & {
    settings?: Record<string, unknown>;
    options?: Record<string, unknown>;
  };

  return Object.assign({}, rule.getDefaultOptions(), candidate.options);
}

function getTestCaseExportName(alias: string): string {
  const name = alias
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, character: string) =>
      character.toUpperCase(),
    )
    .replace(/[^a-zA-Z0-9]/g, '');

  return `${name || 'rule'}RuleTestCases`;
}

function ensureTrailingNewline(text: string): string {
  return text.endsWith('\n') ? text : `${text}\n`;
}

function recreateDirectory(directory: string): void {
  if (existsSync(directory)) {
    rmSync(directory, {
      recursive: true,
      force: true,
    });
  }

  mkdirSync(directory, {
    recursive: true,
  });
}
