import {
  existsSync,
  mkdirSync,
  rmSync,
  writeFileSync,
} from 'fs';
import { join, relative } from 'path';
import dedent from 'ts-dedent';

import { Rule, rules, RuleType, sortRules } from '../../src/rules';
import '../../src/rules-registry';
import { RuleBuilderBase } from '../../src/rules/rule-builder';

/**
 * Generates integration-test suites and their corresponding test-vault
 * fixtures from the examples defined on each rule.
 *
 * Generated integration suites:
 *   __integration__/rule-tests/<rule-alias>.test.ts
 *
 * Generated test-vault files:
 *   test-vault/rule-tests/<rule-alias>/<rule-alias>-<example-number>.md
 *   test-vault/rule-tests/<rule-alias>/<rule-alias>-<example-number>.linted.md
 *
 * The generated directories are deleted and recreated on every run.
 */

const integrationTestsDirectory = './__integration__/rule-tests';
const testVaultDirectory = './test-vault/rule-tests';

const autogenWarning = `// This file was automatically generated. Do not edit it directly.\n` +
  `// Generated by scripts/js/integration-tests.ts.\n\n`;

const skipRules = new Set<string>([
  // uses moment
  'yaml-timestamp',
  'yaml-key-sort',
  // fileName needs a good way of getting set
  'yaml-title',
  'yaml-title-alias',
  'file-name-heading',
  // mispellings need loading for the tests to work...
  'auto-correct-common-misspellings'
]);

sortRules();

generate();

function generate(): void {
  recreateDirectory(integrationTestsDirectory);
  recreateDirectory(testVaultDirectory);

  const rulesAliasesForTestCases: string[] = [];
  for (const rule of rules) {
    if (shouldSkipRule(rule)) {
      console.log(`Skipping ${rule.alias}`);
      continue;
    }

    rulesAliasesForTestCases.push(rule.alias);
    generateRule(rule);
  }

  generateIndex(rulesAliasesForTestCases);

  console.log('Integration tests generated.');
}

function shouldSkipRule(rule: typeof rules[number]): boolean {
  if (rule.type === RuleType.PASTE || skipRules.has(rule.alias)) {
    return true;
  }

  /*
   * Some rules depend on Moment without necessarily exposing that fact
   * through their rule type. Keep the check here deliberately conservative
   * so those rules can be added to the skip list explicitly when needed.
   */
  return false;
}

function generateIndex(ruleAliases: string[]): void {
  const imports: string[] = [];
  const testCaseSuiteNames: string[] = [];
  for (const ruleAlias of ruleAliases) {
    const testSuiteName = getTestCaseExportName(ruleAlias);
    imports.push(`import { ${testSuiteName} } from './${ruleAlias}.test';`);
    testCaseSuiteNames.push('...' + testSuiteName);
  }

  const outputPath = join(integrationTestsDirectory, `index.ts`);

  writeFileSync(outputPath, dedent`
    ${autogenWarning}${imports.join('\n')}

    export const ruleTests = [
      ${testCaseSuiteNames.join(',\n')}
    ];
  `)
}

function generateRule(rule: Rule): void {
  const ruleDirectory = join(testVaultDirectory, rule.alias);

  mkdirSync(ruleDirectory, { recursive: true });

  const setupFunctions: string[] = [];
  const testCases = rule.examples.map((example, index) => {
    const exampleNumber = index + 1;
    const beforePath = join(ruleDirectory, `${rule.alias}-${exampleNumber}.md`);
    const afterPath = join(ruleDirectory, `${rule.alias}-${exampleNumber}.linted.md`);

    writeFileSync(beforePath, example.before);
    writeFileSync(afterPath, example.after);

    const [setupFuncName, setupFunc] = generateSetupFunction(rule, example, exampleNumber);
    if (setupFunc) {
      setupFunctions.push(setupFunc);
    }

    return generateTestCase(rule.alias, example, exampleNumber, setupFuncName);
  });

  const testFile = dedent`
    ${autogenWarning}import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

    ${setupFunctions.join('\n\n')}

    export const ${getTestCaseExportName(rule.alias)}: IntegrationTestCase[] = [
      ${testCases.join(',\n')}
    ];
  `;

  const outputPath = join(integrationTestsDirectory, `${rule.alias}.test.ts`);

  writeFileSync(outputPath, testFile);

  console.log(`Generated ${relative(process.cwd(), outputPath)} (${rule.examples.length} example${rule.examples.length === 1 ? '' : 's'})`,
  );
}

function generateTestCase(ruleAlias: string, example: typeof rules[number]['examples'][number], exampleNumber: number, setupFuncName: string): string {
  const filePath = `rule-tests/${ruleAlias}/${ruleAlias}-${exampleNumber}.md`;

  return dedent`
    {
      name: ${JSON.stringify(example.description)},
      filePath: ${JSON.stringify(filePath)},
      setup: ${setupFuncName},
    }
  `;
}


function getExampleSettings(rule: Rule, example: typeof rules[number]['examples'][number]): { ruleSettings: Record<string, unknown>; commonStyles: Record<string, unknown> } {
  const exampleOptions = example.options as Record<string, unknown>;
  const ruleSettings: Record<string, unknown> = {};
  const commonStyles: Record<string, unknown> = {};
  const builder = RuleBuilderBase.getBuilderByName(rule.alias);

  const commonStyleKeys: Record<string, string> = {
    aliasArrayStyle: 'aliasArrayStyle',
    tagArrayStyle: 'tagArrayStyle',
    defaultArrayStyle: 'defaultArrayStyle',
    defaultEscapeCharacter: 'escapeCharacter',
    minimumNumberOfDollarSignsToBeAMathBlock: 'minimumNumberOfDollarSignsToBeAMathBlock',
    removeUnnecessaryEscapeCharsForMultiLineArrays: 'removeUnnecessaryEscapeCharsForMultiLineArrays',
  };

  for (const [exampleKey, value] of Object.entries(exampleOptions)) {
    const commonStyleKey = commonStyleKeys[exampleKey];

    if (commonStyleKey !== undefined) {
      commonStyles[commonStyleKey] = value;
      continue;
    }

    const optionBuilder = builder.optionBuilders.find(
      optionBuilder => optionBuilder.optionsKey === exampleKey,
    );

    if (!optionBuilder) {
      throw new Error(`Unknown option "${exampleKey}" for rule "${rule.alias}"`);
    }

    ruleSettings[optionBuilder.configKey] = value;
  }

  ruleSettings.enabled = true;

  return { ruleSettings, commonStyles };
}

function generateSetupFunction(rule: Rule, example: typeof rules[number]['examples'][number], exampleNumber: number): [setupFuncName: string, setupFunction: string] {
  const funcName = 'setup' + exampleNumber;

  const {
    ruleSettings,
    commonStyles,
  } = getExampleSettings(rule, example);

  const commonStylesSetup = generateCommonStylesSetup(commonStyles);

  return [funcName, dedent`
    function ${funcName}(plugin: TestLinterPlugin): Promise<void> {
      plugin.plugin.settings.ruleConfigs['${rule.settingsKey}'] = ${JSON.stringify(ruleSettings, null, 2)};${commonStylesSetup}

      return Promise.resolve();
    }
  `];
}

function generateCommonStylesSetup(commonStyles: Record<string, unknown>): string {
  const assignments = Object.entries(commonStyles).map(
    ([key, value]) => dedent`
      plugin.plugin.settings.commonStyles.${key} = ${JSON.stringify(value)};
    `,
  );

  if (assignments.length === 0) {
    return '';
  }

  return '\n\n' + assignments.join('\n');
}

function getTestCaseExportName(alias: string): string {
  const name = alias
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, character: string) =>
      character.toUpperCase(),
    )
    .replace(/[^a-zA-Z0-9]/g, '');

  return `${name || 'rule'}RuleTestCases`;
}

function recreateDirectory(directory: string): void {
  if (existsSync(directory)) {
    rmSync(directory, {
      recursive: true,
      force: true,
    });
  }

  mkdirSync(directory, {
    recursive: true,
  });
}
