import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import {plugin as globImport} from 'rollup-plugin-glob-import';
import replace from '@rollup/plugin-replace';

const isProd = (process.env.BUILD === 'production');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugin's github repository
*/
`;

export default [
  {
    input: 'src/main.ts',
    output: {
      dir: '.',
      sourcemap: 'inline',
      sourcemapExcludeSources: isProd,
      format: 'cjs',
      exports: 'default',
      banner,
    },
    external: ['obsidian'],
    plugins: [
      typescript({inlineSources: !isProd}),
      nodeResolve({browser: true}),
      commonjs(),
      globImport({
        format: 'default',
      }),
    ],
  },
  {
    input: 'src/docs.ts',
    output: {
      dir: '.',
      sourcemap: 'inline',
      format: 'cjs',
      banner,
    },
    external: ['obsidian'],
    plugins: [
      typescript(),
      replace({
        values: {
          'obsidian.moment': 'moment',
          'var obsidian = require(\'obsidian\');': 'var moment = require(\'moment\');',
        },
        preventAssignment: true,
        delimiters: ['', ''],
      }),
      nodeResolve({browser: true}),
      commonjs(),
      globImport({
        format: 'default',
      }),
    ],
  },
];
