// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['align-table-columns'] = {
  "enabled": true
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['align-table-columns'] = {
  "enabled": true
};

    return Promise.resolve();
  }

  function setup3(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['align-table-columns'] = {
  "enabled": true
};

    return Promise.resolve();
  }

export const alignTableColumnsRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Make sure columns are aligned properly",
    filePath: "rule-tests/align-table-columns/align-table-columns-1.md",
    setup: setup1,
  },
  {
    name: "Make sure column alignment works with CJK characters",
    filePath: "rule-tests/align-table-columns/align-table-columns-2.md",
    setup: setup2,
  },
  {
    name: "Missing separators get added to the table if they are missing",
    filePath: "rule-tests/align-table-columns/align-table-columns-3.md",
    setup: setup3,
  }
];