// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

async function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['auto-correct-common-misspellings'] = {
  "enabled": true
};
plugin.plugin.hasLoadedMisspellingFiles = false;

await plugin.plugin.loadAutoCorrectFiles(false);

  return Promise.resolve();
}

async function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['auto-correct-common-misspellings'] = {
  "skip-words-with-multiple-capitals": true,
  "enabled": true
};
plugin.plugin.hasLoadedMisspellingFiles = false;

await plugin.plugin.loadAutoCorrectFiles(false);

  return Promise.resolve();
}

export const autoCorrectCommonMisspellingsRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Auto-correct misspellings in regular text, but not code blocks, math blocks, YAML, or tags",
    filePath: "rule-tests/auto-correct-common-misspellings/auto-correct-common-misspellings-1.md",
    setup: setup1,
  },
  {
    name: "Auto-correct misspellings keeps first letter's case",
    filePath: "rule-tests/auto-correct-common-misspellings/auto-correct-common-misspellings-2.md",
    setup: setup1,
  },
  {
    name: "Links should not be auto-corrected",
    filePath: "rule-tests/auto-correct-common-misspellings/auto-correct-common-misspellings-3.md",
    setup: setup1,
  },
  {
    name: "Auto-correct misspellings skips words with multiple capital letters in them if `Skip Words with Multiple Capitals` is Enabled",
    filePath: "rule-tests/auto-correct-common-misspellings/auto-correct-common-misspellings-4.md",
    setup: setup4,
  }
];