// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['blockquote-style'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['blockquote-style'] = {
  "style": "no space",
  "enabled": true
};

  return Promise.resolve();
}

export const blockquoteStyleRuleTestCases: IntegrationTestCase[] = [
  {
    name: "When style = `space`, a space is added to blockquotes missing a space after the indicator",
    filePath: "rule-tests/blockquote-style/blockquote-style-1.md",
    setup: setup1,
  },
  {
    name: "When style = `no space`, spaces are removed after a blockquote indicator",
    filePath: "rule-tests/blockquote-style/blockquote-style-2.md",
    setup: setup2,
  }
];