// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['capitalize-headings'] = {
  "enabled": true,
  "style": "Title Case",
  "ignore-case-words": true,
  "ignore-words": [],
  "lowercase-words": [],
  "starting-word-ignore-characters": "'\"(‘“-",
  "ending-word-ignore-characters": ".?!,:;'\")”’0123456789-",
  "ignoreCasedWords": false
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['capitalize-headings'] = {
  "enabled": true,
  "style": "Title Case",
  "ignore-case-words": true,
  "ignore-words": [],
  "lowercase-words": [],
  "starting-word-ignore-characters": "'\"(‘“-",
  "ending-word-ignore-characters": ".?!,:;'\")”’0123456789-",
  "ignoreCasedWords": true
};

    return Promise.resolve();
  }

  function setup3(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['capitalize-headings'] = {
  "enabled": true,
  "style": "First letter",
  "ignore-case-words": true,
  "ignore-words": [],
  "lowercase-words": [],
  "starting-word-ignore-characters": "'\"(‘“-",
  "ending-word-ignore-characters": ".?!,:;'\")”’0123456789-"
};

    return Promise.resolve();
  }

  function setup4(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['capitalize-headings'] = {
  "enabled": true,
  "style": "ALL CAPS",
  "ignore-case-words": true,
  "ignore-words": [],
  "lowercase-words": [],
  "starting-word-ignore-characters": "'\"(‘“-",
  "ending-word-ignore-characters": ".?!,:;'\")”’0123456789-"
};

    return Promise.resolve();
  }

export const capitalizeHeadingsRuleTestCases: IntegrationTestCase[] = [
  {
    name: "With `Title case=true`, `Ignore cased words=false`",
    filePath: "rule-tests/capitalize-headings/capitalize-headings-1.md",
    setup: setup1,
  },
  {
    name: "With `Title Case=true`, `Ignore cased words=true`",
    filePath: "rule-tests/capitalize-headings/capitalize-headings-2.md",
    setup: setup2,
  },
  {
    name: "With `First letter=true`",
    filePath: "rule-tests/capitalize-headings/capitalize-headings-3.md",
    setup: setup3,
  },
  {
    name: "With `ALL CAPS=true`",
    filePath: "rule-tests/capitalize-headings/capitalize-headings-4.md",
    setup: setup4,
  }
];