// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['compact-yaml'] = {
  "enabled": true,
  "inner-new-lines": false
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['compact-yaml'] = {
  "enabled": true,
  "inner-new-lines": false,
  "innerNewLines": true
};

    return Promise.resolve();
  }

export const compactYamlRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Remove blank lines at the start and end of the YAML",
    filePath: "rule-tests/compact-yaml/compact-yaml-1.md",
    setup: setup1,
  },
  {
    name: "Remove blank lines anywhere in YAML with inner new lines set to true",
    filePath: "rule-tests/compact-yaml/compact-yaml-2.md",
    setup: setup2,
  }
];