// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['consecutive-blank-lines'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const consecutiveBlankLinesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Consecutive blank lines are removed",
    filePath: "rule-tests/consecutive-blank-lines/consecutive-blank-lines-1.md",
    setup: setup1,
  }
];