// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['convert-bullet-list-markers'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['convert-bullet-list-markers'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const convertBulletListMarkersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Converts •",
    filePath: "rule-tests/convert-bullet-list-markers/convert-bullet-list-markers-1.md",
    setup: setup1,
  },
  {
    name: "Converts §",
    filePath: "rule-tests/convert-bullet-list-markers/convert-bullet-list-markers-2.md",
    setup: setup2,
  }
];