// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['convert-spaces-to-tabs'] = {
  "tabsize": 3,
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['convert-spaces-to-tabs'] = {
  "tabsize": 3,
  "enabled": true
};

  return Promise.resolve();
}

export const convertSpacesToTabsRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Converting spaces to tabs with `tabsize = 3`",
    filePath: "rule-tests/convert-spaces-to-tabs/convert-spaces-to-tabs-1.md",
    setup: setup1,
  },
  {
    name: "Converting spaces to tabs with `tabsize = 3` works in blockquotes",
    filePath: "rule-tests/convert-spaces-to-tabs/convert-spaces-to-tabs-2.md",
    setup: setup2,
  }
];