// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['dedupe-yaml-array-values'] = {
  "enabled": true
};

plugin.plugin.settings.commonStyles.aliasArrayStyle = "multi-line";

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['dedupe-yaml-array-values'] = {
  "ignore-keys": [
    "arr2"
  ],
  "enabled": true
};

plugin.plugin.settings.commonStyles.aliasArrayStyle = "multi-line";

  return Promise.resolve();
}

export const dedupeYamlArrayValuesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Dedupe YAML tags is case sensitive and will use your default format for tags.",
    filePath: "rule-tests/dedupe-yaml-array-values/dedupe-yaml-array-values-1.md",
    setup: setup1,
  },
  {
    name: "Dedupe YAML aliases is case sensitive and will use your default format for aliases.",
    filePath: "rule-tests/dedupe-yaml-array-values/dedupe-yaml-array-values-2.md",
    setup: setup1,
  },
  {
    name: "Dedupe YAML array keys is case sensitive and will try to preserve the original array format.",
    filePath: "rule-tests/dedupe-yaml-array-values/dedupe-yaml-array-values-3.md",
    setup: setup1,
  },
  {
    name: "Dedupe YAML respects list of keys to not remove duplicates of for normal arrays (keys to ignore is just `arr2` for this example)",
    filePath: "rule-tests/dedupe-yaml-array-values/dedupe-yaml-array-values-4.md",
    setup: setup4,
  }
];