// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['default-language-for-code-fences'] = {
  "default-language": "javascript",
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['default-language-for-code-fences'] = {
  "default-language": "shell",
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['default-language-for-code-fences'] = {
  "default-language": "",
  "enabled": true
};

  return Promise.resolve();
}

export const defaultLanguageForCodeFencesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Add a default language `javascript` to code blocks that do not have a language specified",
    filePath: "rule-tests/default-language-for-code-fences/default-language-for-code-fences-1.md",
    setup: setup1,
  },
  {
    name: "If a code block already has a language specified, do not change it",
    filePath: "rule-tests/default-language-for-code-fences/default-language-for-code-fences-2.md",
    setup: setup2,
  },
  {
    name: "Empty string as the default language will not add a language to code blocks",
    filePath: "rule-tests/default-language-for-code-fences/default-language-for-code-fences-3.md",
    setup: setup3,
  }
];