// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['empty-line-around-code-fences'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['empty-line-around-code-fences'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['empty-line-around-code-fences'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['empty-line-around-code-fences'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const emptyLineAroundCodeFencesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Fenced code blocks that start a document do not get an empty line before them.",
    filePath: "rule-tests/empty-line-around-code-fences/empty-line-around-code-fences-1.md",
    setup: setup1,
  },
  {
    name: "Fenced code blocks that end a document do not get an empty line after them.",
    filePath: "rule-tests/empty-line-around-code-fences/empty-line-around-code-fences-2.md",
    setup: setup2,
  },
  {
    name: "Fenced code blocks that are in a blockquote have the proper empty line added",
    filePath: "rule-tests/empty-line-around-code-fences/empty-line-around-code-fences-3.md",
    setup: setup3,
  },
  {
    name: "Nested fenced code blocks get empty lines added around them",
    filePath: "rule-tests/empty-line-around-code-fences/empty-line-around-code-fences-4.md",
    setup: setup4,
  }
];