// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['empty-line-around-blockquotes'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['empty-line-around-blockquotes'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['empty-line-around-blockquotes'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const emptyLineAroundBlockquotesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Blockquotes that start a document do not get an empty line before them.",
    filePath: "rule-tests/empty-line-around-blockquotes/empty-line-around-blockquotes-1.md",
    setup: setup1,
  },
  {
    name: "Blockquotes that end a document do not get an empty line after them.",
    filePath: "rule-tests/empty-line-around-blockquotes/empty-line-around-blockquotes-2.md",
    setup: setup2,
  },
  {
    name: "Blockquotes that are nested have the proper empty line added",
    filePath: "rule-tests/empty-line-around-blockquotes/empty-line-around-blockquotes-3.md",
    setup: setup3,
  }
];