// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['escape-yaml-special-characters'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['escape-yaml-special-characters'] = {
  "enabled": true
};

plugin.plugin.settings.commonStyles.escapeCharacter = "'";

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['escape-yaml-special-characters'] = {
  "try-to-escape-single-line-arrays": true,
  "enabled": true
};

  return Promise.resolve();
}

export const escapeYamlSpecialCharactersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "YAML without anything to escape",
    filePath: "rule-tests/escape-yaml-special-characters/escape-yaml-special-characters-1.md",
    setup: setup1,
  },
  {
    name: "YAML with unescaped values",
    filePath: "rule-tests/escape-yaml-special-characters/escape-yaml-special-characters-2.md",
    setup: setup1,
  },
  {
    name: "YAML with unescaped values in an expanded list with `Default escape character = '`",
    filePath: "rule-tests/escape-yaml-special-characters/escape-yaml-special-characters-3.md",
    setup: setup3,
  },
  {
    name: "YAML with unescaped values with arrays",
    filePath: "rule-tests/escape-yaml-special-characters/escape-yaml-special-characters-4.md",
    setup: setup4,
  }
];