// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['file-name-heading'] = {
  "enabled": true,
  "fileName": "File Name"
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['file-name-heading'] = {
  "enabled": true,
  "fileName": "File Name"
};

  return Promise.resolve();
}

export const fileNameHeadingRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Inserts an H1 heading",
    filePath: "rule-tests/file-name-heading/file-name-heading-1.md",
    setup: setup1,
  },
  {
    name: "Inserts heading after YAML front matter",
    filePath: "rule-tests/file-name-heading/file-name-heading-2.md",
    setup: setup2,
  }
];