// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['footnote-after-punctuation'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const footnoteAfterPunctuationRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Placing footnotes after punctuation.",
    filePath: "rule-tests/footnote-after-punctuation/footnote-after-punctuation-1.md",
    setup: setup1,
  },
  {
    name: "A footnote at the start of a task is not moved to after the punctuation",
    filePath: "rule-tests/footnote-after-punctuation/footnote-after-punctuation-2.md",
    setup: setup1,
  }
];