// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['force-yaml-escape'] = {
  "enabled": true,
  "force-yaml-escape-keys": []
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['force-yaml-escape'] = {
  "enabled": true,
  "force-yaml-escape-keys": [],
  "forceYamlEscape": [
    "key",
    "title",
    "bool"
  ],
  "defaultEscapeCharacter": "\""
};

plugin.plugin.settings.commonStyles.escapeCharacter = '"';

    return Promise.resolve();
  }

export const forceYamlEscapeRuleTestCases: IntegrationTestCase[] = [
  {
    name: "YAML without anything to escape",
    filePath: "rule-tests/force-yaml-escape/force-yaml-escape-1.md",
    setup: setup1,
  },
  {
    name: "Force YAML keys to be escaped with double quotes where not already escaped with `Force YAML escape on keys = 'key'\\n'title'\\n'bool'`",
    filePath: "rule-tests/force-yaml-escape/force-yaml-escape-2.md",
    setup: setup2,
  }
];