// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['format-yaml-array'] = {
  "force-single-line-array-style": [
    "test"
  ],
  "enabled": true
};

plugin.plugin.settings.commonStyles.aliasArrayStyle = "multi-line";

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['format-yaml-array'] = {
  "alias-key": false,
  "enabled": true
};

plugin.plugin.settings.commonStyles.tagArrayStyle = "single string space delimited";

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['format-yaml-array'] = {
  "default-array-keys": true,
  "enabled": true
};

plugin.plugin.settings.commonStyles.defaultArrayStyle = "single-line";

  return Promise.resolve();
}

export const formatYamlArrayRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Format tags as a single-line array delimited by spaces and aliases as a multi-line array and format the key `test` to be a single-line array",
    filePath: "rule-tests/format-yaml-array/format-yaml-array-1.md",
    setup: setup1,
  },
  {
    name: "Format tags as a single string with space delimiters, ignore aliases, and format regular YAML arrays as single-line arrays",
    filePath: "rule-tests/format-yaml-array/format-yaml-array-2.md",
    setup: setup2,
  },
  {
    name: "Arrays with dictionaries in them are ignored",
    filePath: "rule-tests/format-yaml-array/format-yaml-array-3.md",
    setup: setup3,
  }
];