// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['headings-start-line'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const headingsStartLineRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removes spaces prior to a heading",
    filePath: "rule-tests/headings-start-line/headings-start-line-1.md",
    setup: setup1,
  },
  {
    name: "Tags are not affected by this",
    filePath: "rule-tests/headings-start-line/headings-start-line-2.md",
    setup: setup1,
  }
];