// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['header-increment'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['header-increment'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['header-increment'] = {
  "start-at-h2": true,
  "enabled": true
};

  return Promise.resolve();
}

export const headerIncrementRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Heading levels are decremented as needed",
    filePath: "rule-tests/header-increment/header-increment-1.md",
    setup: setup1,
  },
  {
    name: "Skipped headings in sections that would be decremented will result in those headings not having the same meaning",
    filePath: "rule-tests/header-increment/header-increment-2.md",
    setup: setup2,
  },
  {
    name: "When `Start header increment at heading level 2 = true`, H1s become H2s and the other headers are incremented accordingly",
    filePath: "rule-tests/header-increment/header-increment-3.md",
    setup: setup3,
  }
];