// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['heading-blank-lines'] = {
  "enabled": true,
  "bottom": true,
  "empty-line-after-yaml": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['heading-blank-lines'] = {
  "enabled": true,
  "bottom": false,
  "empty-line-after-yaml": true,
  "emptyLineAfterYaml": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['heading-blank-lines'] = {
  "enabled": true,
  "bottom": true,
  "empty-line-after-yaml": true,
  "emptyLineAfterYaml": false
};

  return Promise.resolve();
}

export const headingBlankLinesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Headings should be surrounded by blank lines",
    filePath: "rule-tests/heading-blank-lines/heading-blank-lines-1.md",
    setup: setup1,
  },
  {
    name: "With `Bottom=false`",
    filePath: "rule-tests/heading-blank-lines/heading-blank-lines-2.md",
    setup: setup2,
  },
  {
    name: "Empty line before header and after YAML is removed with `Empty line between YAML and header=false`",
    filePath: "rule-tests/heading-blank-lines/heading-blank-lines-3.md",
    setup: setup3,
  }
];