// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import { addBlankLineAfterYamlRuleTestCases } from './add-blank-line-after-yaml.test';
import { dedupeYamlArrayValuesRuleTestCases } from './dedupe-yaml-array-values.test';
import { escapeYamlSpecialCharactersRuleTestCases } from './escape-yaml-special-characters.test';
import { forceYamlEscapeRuleTestCases } from './force-yaml-escape.test';
import { formatTagsInYamlRuleTestCases } from './format-tags-in-yaml.test';
import { formatYamlArrayRuleTestCases } from './format-yaml-array.test';
import { insertYamlAttributesRuleTestCases } from './insert-yaml-attributes.test';
import { moveInlineFieldsToYamlRuleTestCases } from './move-inline-fields-to-yaml.test';
import { moveTagsToYamlRuleTestCases } from './move-tags-to-yaml.test';
import { removeYamlKeysRuleTestCases } from './remove-yaml-keys.test';
import { sortYamlArrayValuesRuleTestCases } from './sort-yaml-array-values.test';
import { yamlTitleRuleTestCases } from './yaml-title.test';
import { yamlTitleAliasRuleTestCases } from './yaml-title-alias.test';
import { capitalizeHeadingsRuleTestCases } from './capitalize-headings.test';
import { fileNameHeadingRuleTestCases } from './file-name-heading.test';
import { headerIncrementRuleTestCases } from './header-increment.test';
import { headingsStartLineRuleTestCases } from './headings-start-line.test';
import { removeTrailingPunctuationInHeadingRuleTestCases } from './remove-trailing-punctuation-in-heading.test';
import { footnoteAfterPunctuationRuleTestCases } from './footnote-after-punctuation.test';
import { moveFootnotesToTheBottomRuleTestCases } from './move-footnotes-to-the-bottom.test';
import { reIndexFootnotesRuleTestCases } from './re-index-footnotes.test';
import { autoCorrectCommonMisspellingsRuleTestCases } from './auto-correct-common-misspellings.test';
import { blockquoteStyleRuleTestCases } from './blockquote-style.test';
import { convertBulletListMarkersRuleTestCases } from './convert-bullet-list-markers.test';
import { defaultLanguageForCodeFencesRuleTestCases } from './default-language-for-code-fences.test';
import { emphasisStyleRuleTestCases } from './emphasis-style.test';
import { noBareUrlsRuleTestCases } from './no-bare-urls.test';
import { orderedListStyleRuleTestCases } from './ordered-list-style.test';
import { properEllipsisRuleTestCases } from './proper-ellipsis.test';
import { quoteStyleRuleTestCases } from './quote-style.test';
import { removeConsecutiveListMarkersRuleTestCases } from './remove-consecutive-list-markers.test';
import { removeEmptyListMarkersRuleTestCases } from './remove-empty-list-markers.test';
import { removeHyphenatedLineBreaksRuleTestCases } from './remove-hyphenated-line-breaks.test';
import { removeMultipleSpacesRuleTestCases } from './remove-multiple-spaces.test';
import { strongStyleRuleTestCases } from './strong-style.test';
import { twoSpacesBetweenLinesWithContentRuleTestCases } from './two-spaces-between-lines-with-content.test';
import { unorderedListStyleRuleTestCases } from './unordered-list-style.test';
import { alignTableColumnsRuleTestCases } from './align-table-columns.test';
import { compactYamlRuleTestCases } from './compact-yaml.test';
import { consecutiveBlankLinesRuleTestCases } from './consecutive-blank-lines.test';
import { convertSpacesToTabsRuleTestCases } from './convert-spaces-to-tabs.test';
import { emptyLineAroundBlockquotesRuleTestCases } from './empty-line-around-blockquotes.test';
import { emptyLineAroundCodeFencesRuleTestCases } from './empty-line-around-code-fences.test';
import { emptyLineAroundHorizontalRulesRuleTestCases } from './empty-line-around-horizontal-rules.test';
import { emptyLineAroundMathBlocksRuleTestCases } from './empty-line-around-math-blocks.test';
import { emptyLineAroundTablesRuleTestCases } from './empty-line-around-tables.test';
import { headingBlankLinesRuleTestCases } from './heading-blank-lines.test';
import { lineBreakAtDocumentEndRuleTestCases } from './line-break-at-document-end.test';
import { moveMathBlockIndicatorsToTheirOwnLineRuleTestCases } from './move-math-block-indicators-to-their-own-line.test';
import { paragraphBlankLinesRuleTestCases } from './paragraph-blank-lines.test';
import { removeEmptyLinesBetweenListMarkersAndChecklistsRuleTestCases } from './remove-empty-lines-between-list-markers-and-checklists.test';
import { removeLinkSpacingRuleTestCases } from './remove-link-spacing.test';
import { removeSpaceAroundCharactersRuleTestCases } from './remove-space-around-characters.test';
import { removeSpaceBeforeOrAfterCharactersRuleTestCases } from './remove-space-before-or-after-characters.test';
import { spaceAfterListMarkersRuleTestCases } from './space-after-list-markers.test';
import { spaceBetweenChineseJapaneseOrKoreanAndEnglishOrNumbersRuleTestCases } from './space-between-chinese-japanese-or-korean-and-english-or-numbers.test';
import { trailingSpacesRuleTestCases } from './trailing-spaces.test';

export const ruleTests = [
  ...addBlankLineAfterYamlRuleTestCases,
  ...dedupeYamlArrayValuesRuleTestCases,
  ...escapeYamlSpecialCharactersRuleTestCases,
  ...forceYamlEscapeRuleTestCases,
  ...formatTagsInYamlRuleTestCases,
  ...formatYamlArrayRuleTestCases,
  ...insertYamlAttributesRuleTestCases,
  ...moveInlineFieldsToYamlRuleTestCases,
  ...moveTagsToYamlRuleTestCases,
  ...removeYamlKeysRuleTestCases,
  ...sortYamlArrayValuesRuleTestCases,
  ...yamlTitleRuleTestCases,
  ...yamlTitleAliasRuleTestCases,
  ...capitalizeHeadingsRuleTestCases,
  ...fileNameHeadingRuleTestCases,
  ...headerIncrementRuleTestCases,
  ...headingsStartLineRuleTestCases,
  ...removeTrailingPunctuationInHeadingRuleTestCases,
  ...footnoteAfterPunctuationRuleTestCases,
  ...moveFootnotesToTheBottomRuleTestCases,
  ...reIndexFootnotesRuleTestCases,
  ...autoCorrectCommonMisspellingsRuleTestCases,
  ...blockquoteStyleRuleTestCases,
  ...convertBulletListMarkersRuleTestCases,
  ...defaultLanguageForCodeFencesRuleTestCases,
  ...emphasisStyleRuleTestCases,
  ...noBareUrlsRuleTestCases,
  ...orderedListStyleRuleTestCases,
  ...properEllipsisRuleTestCases,
  ...quoteStyleRuleTestCases,
  ...removeConsecutiveListMarkersRuleTestCases,
  ...removeEmptyListMarkersRuleTestCases,
  ...removeHyphenatedLineBreaksRuleTestCases,
  ...removeMultipleSpacesRuleTestCases,
  ...strongStyleRuleTestCases,
  ...twoSpacesBetweenLinesWithContentRuleTestCases,
  ...unorderedListStyleRuleTestCases,
  ...alignTableColumnsRuleTestCases,
  ...compactYamlRuleTestCases,
  ...consecutiveBlankLinesRuleTestCases,
  ...convertSpacesToTabsRuleTestCases,
  ...emptyLineAroundBlockquotesRuleTestCases,
  ...emptyLineAroundCodeFencesRuleTestCases,
  ...emptyLineAroundHorizontalRulesRuleTestCases,
  ...emptyLineAroundMathBlocksRuleTestCases,
  ...emptyLineAroundTablesRuleTestCases,
  ...headingBlankLinesRuleTestCases,
  ...lineBreakAtDocumentEndRuleTestCases,
  ...moveMathBlockIndicatorsToTheirOwnLineRuleTestCases,
  ...paragraphBlankLinesRuleTestCases,
  ...removeEmptyLinesBetweenListMarkersAndChecklistsRuleTestCases,
  ...removeLinkSpacingRuleTestCases,
  ...removeSpaceAroundCharactersRuleTestCases,
  ...removeSpaceBeforeOrAfterCharactersRuleTestCases,
  ...spaceAfterListMarkersRuleTestCases,
  ...spaceBetweenChineseJapaneseOrKoreanAndEnglishOrNumbersRuleTestCases,
  ...trailingSpacesRuleTestCases
];