// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['insert-yaml-attributes'] = {
  "text-to-insert": [
    "aliases:",
    "tags: doc",
    "animal: dog"
  ],
  "enabled": true
};

  return Promise.resolve();
}

export const insertYamlAttributesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Insert static lines into YAML frontmatter. Text to insert: `aliases:\ntags: doc\nanimal: dog`",
    filePath: "rule-tests/insert-yaml-attributes/insert-yaml-attributes-1.md",
    setup: setup1,
  }
];