// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['line-break-at-document-end'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['line-break-at-document-end'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['line-break-at-document-end'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const lineBreakAtDocumentEndRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Appending a line break to the end of the document.",
    filePath: "rule-tests/line-break-at-document-end/line-break-at-document-end-1.md",
    setup: setup1,
  },
  {
    name: "Removing trailing line breaks to the end of the document, except one.",
    filePath: "rule-tests/line-break-at-document-end/line-break-at-document-end-2.md",
    setup: setup2,
  },
  {
    name: "Empty files will not have a blank line added",
    filePath: "rule-tests/line-break-at-document-end/line-break-at-document-end-3.md",
    setup: setup3,
  }
];