// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-math-block-indicators-to-their-own-line'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const moveMathBlockIndicatorsToTheirOwnLineRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Moving math block indicator to its own line when `Number of dollar signs to indicate a math block` = 2",
    filePath: "rule-tests/move-math-block-indicators-to-their-own-line/move-math-block-indicators-to-their-own-line-1.md",
    setup: setup1,
  },
  {
    name: "Moving math block indicator to its own line when `Number of dollar signs to indicate a math block` = 3 and opening indicator is on the same line as the start of the content",
    filePath: "rule-tests/move-math-block-indicators-to-their-own-line/move-math-block-indicators-to-their-own-line-2.md",
    setup: setup1,
  },
  {
    name: "Moving math block indicator to its own line when `Number of dollar signs to indicate a math block` = 2 and ending indicator is on the same line as the ending line of the content",
    filePath: "rule-tests/move-math-block-indicators-to-their-own-line/move-math-block-indicators-to-their-own-line-3.md",
    setup: setup1,
  }
];