// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-tags-to-yaml'] = {
  "tags-to-ignore": [
    "ignored-tag"
  ],
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-tags-to-yaml'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-tags-to-yaml'] = {
  "how-to-handle-existing-tags": "Remove hashtag",
  "tags-to-ignore": [
    "yet-another-ignored-tag"
  ],
  "enabled": true
};

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-tags-to-yaml'] = {
  "how-to-handle-existing-tags": "Remove whole tag",
  "enabled": true
};

  return Promise.resolve();
}

export const moveTagsToYamlRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Move tags from body to YAML with `Tags to ignore = 'ignored-tag'`",
    filePath: "rule-tests/move-tags-to-yaml/move-tags-to-yaml-1.md",
    setup: setup1,
  },
  {
    name: "Move tags from body to YAML with existing tags retains the already existing ones and only adds new ones",
    filePath: "rule-tests/move-tags-to-yaml/move-tags-to-yaml-2.md",
    setup: setup2,
  },
  {
    name: "Move tags to YAML frontmatter and then remove hashtags in body content tags when `Body tag operation = 'Remove hashtag'` and `Tags to ignore = 'yet-another-ignored-tag'`.",
    filePath: "rule-tests/move-tags-to-yaml/move-tags-to-yaml-3.md",
    setup: setup3,
  },
  {
    name: "Move tags to YAML frontmatter and then remove body content tags when `Body tag operation = 'Remove whole tag'`.",
    filePath: "rule-tests/move-tags-to-yaml/move-tags-to-yaml-4.md",
    setup: setup4,
  }
];