// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-footnotes-to-the-bottom'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-footnotes-to-the-bottom'] = {
  "include-blank-line-between-footnotes": true,
  "enabled": true
};

  return Promise.resolve();
}

export const moveFootnotesToTheBottomRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Moving footnotes to the bottom",
    filePath: "rule-tests/move-footnotes-to-the-bottom/move-footnotes-to-the-bottom-1.md",
    setup: setup1,
  },
  {
    name: "Moving footnotes to the bottom with including a blank line between footnotes",
    filePath: "rule-tests/move-footnotes-to-the-bottom/move-footnotes-to-the-bottom-2.md",
    setup: setup2,
  }
];