// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "how-to-handle-bracketed-fields": "Move and remove",
  "enabled": true
};

  return Promise.resolve();
}

function setup5(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "how-to-handle-full-line-fields": "Move and keep in text",
  "enabled": true
};

  return Promise.resolve();
}

function setup6(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "how-to-handle-bracketed-fields": "Move and keep value in text",
  "enabled": true
};

  return Promise.resolve();
}

function setup9(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "how-to-handle-existing-keys": "Merge into list",
  "enabled": true
};

  return Promise.resolve();
}

function setup10(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "enabled": true
};

plugin.plugin.settings.commonStyles.defaultArrayStyle = "multi-line";

  return Promise.resolve();
}

function setup12(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "how-to-handle-existing-keys": "Overwrite",
  "enabled": true
};

  return Promise.resolve();
}

function setup13(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['move-inline-fields-to-yaml'] = {
  "inline-keys-to-ignore": [
    "related"
  ],
  "enabled": true
};

  return Promise.resolve();
}

export const moveInlineFieldsToYamlRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Moves full-line fields to the YAML frontmatter and removes their lines while leaving list items, bracketed fields, and code alone",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-1.md",
    setup: setup1,
  },
  {
    name: "Leaves fields in tables and comments alone since removing a line from them would change their contents",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-2.md",
    setup: setup2,
  },
  {
    name: "Keys that are not plain YAML keys are escaped and Markdown around a full-line key is removed",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-3.md",
    setup: setup1,
  },
  {
    name: "Tags have their hashtags removed and tags and aliases are split up and use the tag and alias array styles from the general settings",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-4.md",
    setup: setup1,
  },
  {
    name: "Adds full-line fields to the YAML frontmatter and leaves their lines, including any Markdown or emoji around the key, as they are when `Full-line inline fields = 'Move and keep in text'`",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-5.md",
    setup: setup5,
  },
  {
    name: "Moves bracketed fields and keeps their values in the text when `Bracketed inline fields = 'Move and keep value in text'`",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-6.md",
    setup: setup6,
  },
  {
    name: "Moves bracketed fields and removes them when `Bracketed inline fields = 'Move and remove'`, removing lines that are left with only whitespace",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-7.md",
    setup: setup2,
  },
  {
    name: "Leaves fields whose key is already in the YAML frontmatter alone when `When the key already exists = 'Skip'`",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-8.md",
    setup: setup1,
  },
  {
    name: "Adds values to the existing key when `When the key already exists = 'Merge into list'`",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-9.md",
    setup: setup9,
  },
  {
    name: "A key found more than once becomes an array that uses the default array style from the general settings",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-10.md",
    setup: setup10,
  },
  {
    name: "Leaves fields in the body when `When the key already exists = 'Merge into list'` and the existing value is a block scalar, a map, or has a YAML comment, since those cannot be turned into a list without losing part of them",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-11.md",
    setup: setup9,
  },
  {
    name: "Replaces the value of the existing key when `When the key already exists = 'Overwrite'`",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-12.md",
    setup: setup12,
  },
  {
    name: "Leaves fields alone when their key is in `Inline keys to ignore = 'related'`",
    filePath: "rule-tests/move-inline-fields-to-yaml/move-inline-fields-to-yaml-13.md",
    setup: setup13,
  }
];