// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['no-bare-urls'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['no-bare-urls'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['no-bare-urls'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['no-bare-urls'] = {
  "no-bare-uris": true,
  "enabled": true
};

  return Promise.resolve();
}

export const noBareUrlsRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Make sure that links are inside of angle brackets when not in single quotes('), double quotes(\"), or backticks(`)",
    filePath: "rule-tests/no-bare-urls/no-bare-urls-1.md",
    setup: setup1,
  },
  {
    name: "Angle brackets are added if the url is not the only text in the single quotes(') or double quotes(\")",
    filePath: "rule-tests/no-bare-urls/no-bare-urls-2.md",
    setup: setup2,
  },
  {
    name: "Multiple angle brackets at the start and or end of a url will be reduced down to 1",
    filePath: "rule-tests/no-bare-urls/no-bare-urls-3.md",
    setup: setup3,
  },
  {
    name: "Puts angle brackets around URIs when `No Bare URIs` is enabled",
    filePath: "rule-tests/no-bare-urls/no-bare-urls-4.md",
    setup: setup4,
  }
];