// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": "."
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": "."
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": ".",
  "numberStyle": "lazy"
};

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": "."
};

  return Promise.resolve();
}

function setup5(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": ".",
  "listEndStyle": ")",
  "numberStyle": "lazy"
};

  return Promise.resolve();
}

function setup6(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": ".",
  "numberStyle": "ascending",
  "preserveStart": true
};

  return Promise.resolve();
}

function setup7(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": ".",
  "preserveStart": true
};

  return Promise.resolve();
}

function setup8(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": ".",
  "numberStyle": "lazy",
  "preserveStart": true
};

  return Promise.resolve();
}

function setup9(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": ".",
  "numberStyle": "lazy",
  "preserveStart": true
};

  return Promise.resolve();
}

function setup10(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['ordered-list-style'] = {
  "enabled": true,
  "number-style": "ascending",
  "list-end-style": ".",
  "numberStyle": "preserve"
};

  return Promise.resolve();
}

export const orderedListStyleRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Ordered lists have list items set to ascending numerical order when Number style is `ascending`.",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-1.md",
    setup: setup1,
  },
  {
    name: "Nested ordered lists have list items set to ascending numerical order when Number style is `ascending`.",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-2.md",
    setup: setup2,
  },
  {
    name: "Ordered list in blockquote has list items set to '1.' when Number style is `lazy`.",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-3.md",
    setup: setup3,
  },
  {
    name: "Ordered list in blockquote has list items set to ascending numerical order when Number style is `ascending`.",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-4.md",
    setup: setup4,
  },
  {
    name: "Nested ordered list has list items set to '1)' when Number style is `lazy` and Ordered list indicator end style is `)`.",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-5.md",
    setup: setup5,
  },
  {
    name: "Ordered lists have list items set to ascending numerical order using initial indicator number when Number style is `ascending` and `preserveStart` is enabled",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-6.md",
    setup: setup6,
  },
  {
    name: "Nested ordered lists have list items set to ascending numerical order using initial indicator number when Number style is `ascending` and `preserveStart` is enabled",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-7.md",
    setup: setup7,
  },
  {
    name: "Ordered lists have list items set to initial indicator number when Number style is `lazy` and `preserveStart` is enabled",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-8.md",
    setup: setup8,
  },
  {
    name: "Nested ordered lists have list items set to initial indicator number when Number style is `lazy` and `preserveStart` is enabled",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-9.md",
    setup: setup9,
  },
  {
    name: "Ordered lists items are not modified when Number style is `preserve`",
    filePath: "rule-tests/ordered-list-style/ordered-list-style-10.md",
    setup: setup10,
  }
];