// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['proper-ellipsis'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const properEllipsisRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Replacing three consecutive dots with an ellipsis.",
    filePath: "rule-tests/proper-ellipsis/proper-ellipsis-1.md",
    setup: setup1,
  }
];