// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['quote-style'] = {
  "enabled": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['quote-style'] = {
  "single-quote-style": "‘’",
  "double-quote-style": "“”",
  "enabled": true
};

  return Promise.resolve();
}

export const quoteStyleRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Smart quotes used in file are converted to straight quotes when styles are set to `Straight`",
    filePath: "rule-tests/quote-style/quote-style-1.md",
    setup: setup1,
  },
  {
    name: "Straight quotes used in file are converted to smart quotes when styles are set to `Smart`",
    filePath: "rule-tests/quote-style/quote-style-2.md",
    setup: setup2,
  }
];