// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-space-around-characters'] = {
  "enabled": true,
  "include-fullwidth-forms": true,
  "include-cjk-symbols-and-punctuation": true,
  "include-dashes": true,
  "other-symbols": ""
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-space-around-characters'] = {
  "enabled": true,
  "include-fullwidth-forms": true,
  "include-cjk-symbols-and-punctuation": true,
  "include-dashes": true,
  "other-symbols": ""
};

  return Promise.resolve();
}

export const removeSpaceAroundCharactersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Remove spaces and tabs around fullwidth characters",
    filePath: "rule-tests/remove-space-around-characters/remove-space-around-characters-1.md",
    setup: setup1,
  },
  {
    name: "Fullwidth characters in list do not affect list markdown syntax",
    filePath: "rule-tests/remove-space-around-characters/remove-space-around-characters-2.md",
    setup: setup2,
  }
];