// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-empty-list-markers'] = {
  "enabled": true
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-empty-list-markers'] = {
  "enabled": true
};

    return Promise.resolve();
  }

  function setup3(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-empty-list-markers'] = {
  "enabled": true
};

    return Promise.resolve();
  }

  function setup4(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-empty-list-markers'] = {
  "enabled": true
};

    return Promise.resolve();
  }

export const removeEmptyListMarkersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removes empty list markers.",
    filePath: "rule-tests/remove-empty-list-markers/remove-empty-list-markers-1.md",
    setup: setup1,
  },
  {
    name: "Removes empty ordered list markers.",
    filePath: "rule-tests/remove-empty-list-markers/remove-empty-list-markers-2.md",
    setup: setup2,
  },
  {
    name: "Removes empty checklist markers.",
    filePath: "rule-tests/remove-empty-list-markers/remove-empty-list-markers-3.md",
    setup: setup3,
  },
  {
    name: "Removes empty list, checklist, and ordered list markers in callouts/blockquotes",
    filePath: "rule-tests/remove-empty-list-markers/remove-empty-list-markers-4.md",
    setup: setup4,
  }
];