// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-empty-lines-between-list-markers-and-checklists'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const removeEmptyLinesBetweenListMarkersAndChecklistsRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Blank lines are removed between ordered list items",
    filePath: "rule-tests/remove-empty-lines-between-list-markers-and-checklists/remove-empty-lines-between-list-markers-and-checklists-1.md",
    setup: setup1,
  },
  {
    name: "Blank lines are removed between list items when the list marker is '-'",
    filePath: "rule-tests/remove-empty-lines-between-list-markers-and-checklists/remove-empty-lines-between-list-markers-and-checklists-2.md",
    setup: setup1,
  },
  {
    name: "Blank lines are removed between checklist items",
    filePath: "rule-tests/remove-empty-lines-between-list-markers-and-checklists/remove-empty-lines-between-list-markers-and-checklists-3.md",
    setup: setup1,
  },
  {
    name: "Blank lines are removed between list items when the list marker is '+'",
    filePath: "rule-tests/remove-empty-lines-between-list-markers-and-checklists/remove-empty-lines-between-list-markers-and-checklists-4.md",
    setup: setup1,
  },
  {
    name: "Blank lines are removed between list items when the list marker is '*'",
    filePath: "rule-tests/remove-empty-lines-between-list-markers-and-checklists/remove-empty-lines-between-list-markers-and-checklists-5.md",
    setup: setup1,
  },
  {
    name: "Blanks lines are removed between like list types (ordered, specific list item markers, and checklists) while blanks are left between different kinds of list item markers",
    filePath: "rule-tests/remove-empty-lines-between-list-markers-and-checklists/remove-empty-lines-between-list-markers-and-checklists-6.md",
    setup: setup1,
  }
];