// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-link-spacing'] = {
  "enabled": true
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-link-spacing'] = {
  "enabled": true
};

    return Promise.resolve();
  }

export const removeLinkSpacingRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Space in regular markdown link text",
    filePath: "rule-tests/remove-link-spacing/remove-link-spacing-1.md",
    setup: setup1,
  },
  {
    name: "Space in wiki link text",
    filePath: "rule-tests/remove-link-spacing/remove-link-spacing-2.md",
    setup: setup2,
  }
];