// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-trailing-punctuation-in-heading'] = {
  "enabled": true,
  "punctuation-to-remove": ".,;:!。，；：！"
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-trailing-punctuation-in-heading'] = {
  "enabled": true,
  "punctuation-to-remove": ".,;:!。，；：！"
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-trailing-punctuation-in-heading'] = {
  "enabled": true,
  "punctuation-to-remove": ".,;:!。，；：！"
};

  return Promise.resolve();
}

export const removeTrailingPunctuationInHeadingRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removes punctuation from the end of a heading",
    filePath: "rule-tests/remove-trailing-punctuation-in-heading/remove-trailing-punctuation-in-heading-1.md",
    setup: setup1,
  },
  {
    name: "HTML Entities at the end of a heading is ignored",
    filePath: "rule-tests/remove-trailing-punctuation-in-heading/remove-trailing-punctuation-in-heading-2.md",
    setup: setup2,
  },
  {
    name: "Removes punctuation from the end of a heading when followed by whitespace",
    filePath: "rule-tests/remove-trailing-punctuation-in-heading/remove-trailing-punctuation-in-heading-3.md",
    setup: setup3,
  }
];