// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-consecutive-list-markers'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const removeConsecutiveListMarkersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removing consecutive list markers.",
    filePath: "rule-tests/remove-consecutive-list-markers/remove-consecutive-list-markers-1.md",
    setup: setup1,
  }
];