// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-space-before-or-after-characters'] = {
  "enabled": true,
  "characters-to-remove-space-before": ",!?;:).’”]",
  "characters-to-remove-space-after": "¿¡‘“(["
};

    return Promise.resolve();
  }

export const removeSpaceBeforeOrAfterCharactersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Remove spaces and tabs before and after default symbol set",
    filePath: "rule-tests/remove-space-before-or-after-characters/remove-space-before-or-after-characters-1.md",
    setup: setup1,
  }
];