// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-multiple-spaces'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const removeMultipleSpacesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removing double and triple space.",
    filePath: "rule-tests/remove-multiple-spaces/remove-multiple-spaces-1.md",
    setup: setup1,
  }
];