// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['remove-yaml-keys'] = {
  "enabled": true,
  "yaml-keys-to-remove": [],
  "yamlKeysToRemove": [
    "status:",
    "keywords",
    "date"
  ]
};

    return Promise.resolve();
  }

export const removeYamlKeysRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removes the values specified in `YAML keys to remove` = \"status:\nkeywords\ndate\"",
    filePath: "rule-tests/remove-yaml-keys/remove-yaml-keys-1.md",
    setup: setup1,
  }
];