// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['remove-hyphenated-line-breaks'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const removeHyphenatedLineBreaksRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removing hyphenated line breaks.",
    filePath: "rule-tests/remove-hyphenated-line-breaks/remove-hyphenated-line-breaks-1.md",
    setup: setup1,
  }
];