// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['sort-yaml-array-values'] = {
  "enabled": true
};

plugin.plugin.settings.commonStyles.aliasArrayStyle = "multi-line";

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['sort-yaml-array-values'] = {
  "sort-order": "Descending Alphabetical",
  "enabled": true
};

plugin.plugin.settings.commonStyles.aliasArrayStyle = "multi-line";

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['sort-yaml-array-values'] = {
  "ignore-keys": [
    "arr2"
  ],
  "enabled": true
};

plugin.plugin.settings.commonStyles.aliasArrayStyle = "multi-line";

  return Promise.resolve();
}

export const sortYamlArrayValuesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Sorting YAML array values alphabetically",
    filePath: "rule-tests/sort-yaml-array-values/sort-yaml-array-values-1.md",
    setup: setup1,
  },
  {
    name: "Sorting YAML array values to be alphabetically descending",
    filePath: "rule-tests/sort-yaml-array-values/sort-yaml-array-values-2.md",
    setup: setup2,
  },
  {
    name: "Sort YAML arrays respects list of keys to not sort values of for normal arrays (keys to ignore is just `arr2` for this example)",
    filePath: "rule-tests/sort-yaml-array-values/sort-yaml-array-values-3.md",
    setup: setup3,
  }
];