// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['space-between-chinese-japanese-or-korean-and-english-or-numbers'] = {
  "enabled": true
};

  return Promise.resolve();
}

export const spaceBetweenChineseJapaneseOrKoreanAndEnglishOrNumbersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Space between Chinese and English",
    filePath: "rule-tests/space-between-chinese-japanese-or-korean-and-english-or-numbers/space-between-chinese-japanese-or-korean-and-english-or-numbers-1.md",
    setup: setup1,
  },
  {
    name: "Space between Chinese and link",
    filePath: "rule-tests/space-between-chinese-japanese-or-korean-and-english-or-numbers/space-between-chinese-japanese-or-korean-and-english-or-numbers-2.md",
    setup: setup1,
  },
  {
    name: "Space between Chinese and inline code block",
    filePath: "rule-tests/space-between-chinese-japanese-or-korean-and-english-or-numbers/space-between-chinese-japanese-or-korean-and-english-or-numbers-3.md",
    setup: setup1,
  },
  {
    name: "No space between Chinese and English in tag",
    filePath: "rule-tests/space-between-chinese-japanese-or-korean-and-english-or-numbers/space-between-chinese-japanese-or-korean-and-english-or-numbers-4.md",
    setup: setup1,
  },
  {
    name: "Make sure that spaces are not added between italics and Chinese characters to preserve markdown syntax",
    filePath: "rule-tests/space-between-chinese-japanese-or-korean-and-english-or-numbers/space-between-chinese-japanese-or-korean-and-english-or-numbers-5.md",
    setup: setup1,
  },
  {
    name: "Images and links are ignored",
    filePath: "rule-tests/space-between-chinese-japanese-or-korean-and-english-or-numbers/space-between-chinese-japanese-or-korean-and-english-or-numbers-6.md",
    setup: setup1,
  },
  {
    name: "Space between CJK and English",
    filePath: "rule-tests/space-between-chinese-japanese-or-korean-and-english-or-numbers/space-between-chinese-japanese-or-korean-and-english-or-numbers-7.md",
    setup: setup1,
  }
];