// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['space-after-list-markers'] = {
  "enabled": true
};

    return Promise.resolve();
  }

export const spaceAfterListMarkersRuleTestCases: IntegrationTestCase[] = [
  {
    name: "A single space is left between the list marker and the text of the list item",
    filePath: "rule-tests/space-after-list-markers/space-after-list-markers-1.md",
    setup: setup1,
  }
];