// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['strong-style'] = {
  "enabled": true,
  "style": "underscore"
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['strong-style'] = {
  "enabled": true,
  "style": "asterisk"
};

    return Promise.resolve();
  }

  function setup3(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['strong-style'] = {
  "enabled": true,
  "style": "consistent"
};

    return Promise.resolve();
  }

  function setup4(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['strong-style'] = {
  "enabled": true,
  "style": "consistent"
};

    return Promise.resolve();
  }

export const strongStyleRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Strong indicators should use underscores when style is set to 'underscore'",
    filePath: "rule-tests/strong-style/strong-style-1.md",
    setup: setup1,
  },
  {
    name: "Strong indicators should use asterisks when style is set to 'asterisk'",
    filePath: "rule-tests/strong-style/strong-style-2.md",
    setup: setup2,
  },
  {
    name: "Strong indicators should use consistent style based on first strong indicator in a file when style is set to 'consistent'",
    filePath: "rule-tests/strong-style/strong-style-3.md",
    setup: setup3,
  },
  {
    name: "Strong indicators should use consistent style based on first strong indicator in a file when style is set to 'consistent'",
    filePath: "rule-tests/strong-style/strong-style-4.md",
    setup: setup4,
  }
];