// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['trailing-spaces'] = {
  "enabled": true,
  "two-space-line-break": false
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['trailing-spaces'] = {
  "enabled": true,
  "two-space-line-break": false,
  "twoSpaceLineBreak": true
};

  return Promise.resolve();
}

export const trailingSpacesRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Removes trailing spaces and tabs.",
    filePath: "rule-tests/trailing-spaces/trailing-spaces-1.md",
    setup: setup1,
  },
  {
    name: "With `Two space linebreak = true`",
    filePath: "rule-tests/trailing-spaces/trailing-spaces-2.md",
    setup: setup2,
  }
];