// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['two-spaces-between-lines-with-content'] = {
  "enabled": true,
  "line-break-indicator": "  ",
  "lineBreakIndicator": "  "
};

  return Promise.resolve();
}

export const twoSpacesBetweenLinesWithContentRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Make sure two spaces are added to the ends of lines that have content on it and the next line for lists, blockquotes, and paragraphs when the line break indicator is `  `",
    filePath: "rule-tests/two-spaces-between-lines-with-content/two-spaces-between-lines-with-content-1.md",
    setup: setup1,
  }
];