// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

  function setup1(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['unordered-list-style'] = {
  "enabled": true,
  "list-style": "consistent"
};

    return Promise.resolve();
  }

  function setup2(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['unordered-list-style'] = {
  "enabled": true,
  "list-style": "consistent",
  "listStyle": "-"
};

    return Promise.resolve();
  }

  function setup3(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['unordered-list-style'] = {
  "enabled": true,
  "list-style": "consistent",
  "listStyle": "*"
};

    return Promise.resolve();
  }

  function setup4(plugin: TestLinterPlugin): Promise<void> {
    plugin.plugin.settings.ruleConfigs['unordered-list-style'] = {
  "enabled": true,
  "list-style": "consistent",
  "listStyle": "+"
};

    return Promise.resolve();
  }

export const unorderedListStyleRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Unordered lists have their marker updated to `*` when `List item style = 'consistent'` and `*` is the first unordered list marker",
    filePath: "rule-tests/unordered-list-style/unordered-list-style-1.md",
    setup: setup1,
  },
  {
    name: "Unordered lists have their marker updated to `-` when `List item style = '-'`",
    filePath: "rule-tests/unordered-list-style/unordered-list-style-2.md",
    setup: setup2,
  },
  {
    name: "Unordered lists have their marker updated to `*` when `List item style = '*'`",
    filePath: "rule-tests/unordered-list-style/unordered-list-style-3.md",
    setup: setup3,
  },
  {
    name: "Unordered list in blockquote has list item markers set to `+` when `List item style = '-'`",
    filePath: "rule-tests/unordered-list-style/unordered-list-style-4.md",
    setup: setup4,
  }
];