// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title-alias'] = {
  "enabled": true,
  "preserve-existing-alias-section-style": true,
  "keep-alias-that-matches-the-filename": false,
  "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
  "alias-helper-key": "linter-yaml-title-alias",
  "remove-alias-if-empty": true
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title-alias'] = {
  "enabled": true,
  "preserve-existing-alias-section-style": true,
  "keep-alias-that-matches-the-filename": false,
  "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
  "alias-helper-key": "linter-yaml-title-alias",
  "remove-alias-if-empty": true,
  "useYamlKeyToKeepTrackOfOldFilenameOrHeading": false
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title-alias'] = {
  "enabled": true,
  "preserve-existing-alias-section-style": true,
  "keep-alias-that-matches-the-filename": false,
  "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
  "alias-helper-key": "linter-yaml-title-alias",
  "remove-alias-if-empty": true,
  "fileName": "Filename",
  "keepAliasThatMatchesTheFilename": true
};

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title-alias'] = {
  "enabled": true,
  "preserve-existing-alias-section-style": true,
  "keep-alias-that-matches-the-filename": false,
  "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
  "alias-helper-key": "linter-yaml-title-alias",
  "remove-alias-if-empty": true,
  "fileName": "Filename",
  "keepAliasThatMatchesTheFilename": true,
  "useYamlKeyToKeepTrackOfOldFilenameOrHeading": false
};

  return Promise.resolve();
}

function setup5(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title-alias'] = {
  "enabled": true,
  "preserve-existing-alias-section-style": true,
  "keep-alias-that-matches-the-filename": false,
  "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
  "alias-helper-key": "linter-yaml-title-alias",
  "remove-alias-if-empty": true,
  "fileName": "Filename",
  "keepAliasThatMatchesTheFilename": true
};

  return Promise.resolve();
}

function setup6(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title-alias'] = {
  "enabled": true,
  "preserve-existing-alias-section-style": true,
  "keep-alias-that-matches-the-filename": false,
  "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
  "alias-helper-key": "linter-yaml-title-alias",
  "remove-alias-if-empty": true,
  "aliasArrayStyle": "multi-line"
};

  return Promise.resolve();
}

function setup7(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title-alias'] = {
  "enabled": true,
  "preserve-existing-alias-section-style": true,
  "keep-alias-that-matches-the-filename": false,
  "use-yaml-key-to-keep-track-of-old-filename-or-heading": true,
  "alias-helper-key": "linter-yaml-title-alias",
  "remove-alias-if-empty": true,
  "fileName": "Filename",
  "keepAliasThatMatchesTheFilename": true,
  "aliasArrayStyle": "multi-line",
  "aliasHelperKey": "title"
};

  return Promise.resolve();
}

export const yamlTitleAliasRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Adds a header with the title from heading.",
    filePath: "rule-tests/yaml-title-alias/yaml-title-alias-1.md",
    setup: setup1,
  },
  {
    name: "Adds a header with the title from heading without YAML key when the use of the YAML key is set to false.",
    filePath: "rule-tests/yaml-title-alias/yaml-title-alias-2.md",
    setup: setup2,
  },
  {
    name: "Adds a header with the title.",
    filePath: "rule-tests/yaml-title-alias/yaml-title-alias-3.md",
    setup: setup3,
  },
  {
    name: "Adds a header with the title without YAML key when the use of the YAML key is set to false.",
    filePath: "rule-tests/yaml-title-alias/yaml-title-alias-4.md",
    setup: setup4,
  },
  {
    name: "Replaces old filename with new filename when no header is present and filename is different than the old one listed in `linter-yaml-title-alias`.",
    filePath: "rule-tests/yaml-title-alias/yaml-title-alias-5.md",
    setup: setup5,
  },
  {
    name: "Make sure that markdown and wiki links in first H1 get their values converted to text",
    filePath: "rule-tests/yaml-title-alias/yaml-title-alias-6.md",
    setup: setup6,
  },
  {
    name: "Using `title` as `Alias helper key` sets the value of `title` to the alias.",
    filePath: "rule-tests/yaml-title-alias/yaml-title-alias-7.md",
    setup: setup7,
  }
];