// This file was automatically generated. Do not edit it directly.
// Generated by scripts/js/integration-tests.ts.

import TestLinterPlugin, {IntegrationTestCase} from '../main.test';

function setup1(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title'] = {
  "enabled": true,
  "title-key": "title",
  "mode": "first-h1-or-filename-if-h1-missing",
  "fileName": "Filename"
};

  return Promise.resolve();
}

function setup2(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title'] = {
  "enabled": true,
  "title-key": "title",
  "mode": "first-h1-or-filename-if-h1-missing",
  "fileName": "Filename"
};

  return Promise.resolve();
}

function setup3(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title'] = {
  "enabled": true,
  "title-key": "title",
  "mode": "first-h1-or-filename-if-h1-missing"
};

  return Promise.resolve();
}

function setup4(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title'] = {
  "enabled": true,
  "title-key": "title",
  "mode": "first-h1",
  "fileName": "Filename"
};

  return Promise.resolve();
}

function setup5(plugin: TestLinterPlugin): Promise<void> {
  plugin.plugin.settings.ruleConfigs['yaml-title'] = {
  "enabled": true,
  "title-key": "title",
  "mode": "filename",
  "fileName": "Filename"
};

  return Promise.resolve();
}

export const yamlTitleRuleTestCases: IntegrationTestCase[] = [
  {
    name: "Adds a header with the title from heading when `mode = 'First H1 or filename if H1 missing'`.",
    filePath: "rule-tests/yaml-title/yaml-title-1.md",
    setup: setup1,
  },
  {
    name: "Adds a header with the title when `mode = 'First H1 or filename if H1 missing'`.",
    filePath: "rule-tests/yaml-title/yaml-title-2.md",
    setup: setup2,
  },
  {
    name: "Make sure that markdown links in headings are properly copied to the YAML as just the text when `mode = 'First H1 or filename if H1 missing'`",
    filePath: "rule-tests/yaml-title/yaml-title-3.md",
    setup: setup3,
  },
  {
    name: "When `mode = 'First H1'`, title does not have a value if no H1 is present",
    filePath: "rule-tests/yaml-title/yaml-title-4.md",
    setup: setup4,
  },
  {
    name: "When `mode = 'Filename'`, title uses the filename ignoring all H1s. Note: the filename is \"Filename\" in this example.",
    filePath: "rule-tests/yaml-title/yaml-title-5.md",
    setup: setup5,
  }
];